### ISSUE TITLE
g++: error: CreateProcess: No such file or directory

### ISSUE THREAD

**Issue by sunbrando** [hu243285237/Cpp_Study#1]
![QQ截图20190906003401](https://user-images.githubusercontent.com/9989440/64362390-08c39d80-d041-11e9-9a0f-19140ebb5573.png)
按你的步骤配置C++环境，编译时候会报这个错误，然后我在MinGW再安装了binutils，就编译过了，不知道你是不是漏了说这一步。
![QQ截图20190906003307](https://user-images.githubusercontent.com/9989440/64362552-4cb6a280-d041-11e9-8a94-4439fd224b11.png)

**Comment by hu243285237** [comment]
只要勾选了mingw32-gcc-bin或mingw32-gcc-g++-bin，mingw32-binutils-bin也会自动勾上的
